name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build with Conan on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Setup the environment
        run: $( [ $(uname -s) = "Darwin" ] && echo brew || echo sudo apt-get -yq ) install ghostscript
      - name: Download source files
        uses: actions/checkout@v3.0.0
      - name: Setup python
        uses: actions/setup-python@v3.0.0
      - name: Install conan
        run : python3 -m pip install conan
      - name: Compile minilibX
        run: |
          export CONAN_SYSREQUIRES_MODE=enabled
          conan install . -o minilibx:shared=False
          conan build .
          conan export-pkg .
      - name: Compile tests
        run: ( cd test ; conan install . --options="minilibx:shared=False" ; make )
      - name: Generate documentation
        run: make doc
