name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-X11:
    runs-on: ubuntu-latest
    steps:
    - name: Download source files
      uses: actions/checkout@v2
    - name: Configure
      run: ./configure
    - name: Compile
      run: make
    - name: Generate documentation
      run: make pdf
    - name: Upload documentation
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Documentation
        path: doc
    - name: Clean
      run: make fclean

  build-MacOSX:
    runs-on: macos-latest
    steps:
    - name: Download source files
      uses: actions/checkout@v2
    - name: Configure
      run: ./configure
    - name: Compile
      run: make
    - name: Clean
      run: make fclean
