name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-X11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: Generate documentation
      run: make pdf
    - name: Upload documentation
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Man pages
        path: doc

  build-MacOSX:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
