name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Setup the environment
      run: |
        test $(uname -s) != "Darwin" || brew install ghostscript
        test $(uname -s) = "Darwin" || sudo apt-get install libx11-dev libxext-dev libxpm-dev
    - name: Download source files
      uses: actions/checkout@v2
    - name: Configure
      run: ./configure
    - name: Compile
      run: make
    - name: Compile tests
      run: make test
    - name: Generate documentation
      run: make doc
#    - name: Upload documentation
#      uses: actions/upload-artifact@v1.0.0
#      with:
#        name: Documentation
#        path: doc
    - name: Clean
      run: make fclean
